"""add user oauth data

迁移 ID: 4f2c8e1a9b3d
父迁移: 68a04ea31d05
创建时间: 2026-04-01 12:00:00.000000

为 /friend 好友功能新增每个绑定用户的 osu! OAuth 用户级令牌表。
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "4f2c8e1a9b3d"
down_revision: str | Sequence[str] | None = "8c6e1a4d9b72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_osubot_useroauthdata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("osu_id", sa.Integer(), nullable=False),
        sa.Column("osu_name", sa.Text(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_osubot_useroauthdata")),
        info={"bind_key": "nonebot_plugin_osubot"},
    )
    with op.batch_alter_table("nonebot_plugin_osubot_useroauthdata", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nonebot_plugin_osubot_useroauthdata_user_id"), ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_osubot_useroauthdata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_osubot_useroauthdata_user_id"))

    op.drop_table("nonebot_plugin_osubot_useroauthdata")
    # ### end Alembic commands ###
