"""add g0v0 user data

迁移 ID: a7b9c1d3e5f7
父迁移: 4f2c8e1a9b3d
创建时间: 2026-08-28 12:00:00.000000

为 /gubind 绑定新增 g0v0（咕哦服）服务器用户表（&gu 后缀查询使用）。
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a7b9c1d3e5f7"
down_revision: str | Sequence[str] | None = "4f2c8e1a9b3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_osubot_g0v0userdata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("osu_id", sa.Integer(), nullable=False),
        sa.Column("osu_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_osubot_g0v0userdata")),
        info={"bind_key": "nonebot_plugin_osubot"},
    )
    with op.batch_alter_table("nonebot_plugin_osubot_g0v0userdata", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nonebot_plugin_osubot_g0v0userdata_user_id"), ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_osubot_g0v0userdata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_osubot_g0v0userdata_user_id"))

    op.drop_table("nonebot_plugin_osubot_g0v0userdata")
    # ### end Alembic commands ###
