"""add g0v0 user data mode

迁移 ID: a8b0c2d4e6f8
父迁移: a7b9c1d3e5f7
创建时间: 2026-08-28 21:20:00.000000

为 g0v0（咕哦服）绑定表新增独立默认模式列（/mode:4 &gu 修改），
与官方绑定的默认模式互不影响。
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "a8b0c2d4e6f8"
down_revision: str | Sequence[str] | None = "a7b9c1d3e5f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_osubot_g0v0userdata", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "osu_mode",
                sa.Integer(),
                server_default="0",
                nullable=False,
                info={"bind_key": "nonebot_plugin_osubot"},
            )
        )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_osubot_g0v0userdata", schema=None) as batch_op:
        batch_op.drop_column("osu_mode")
    # ### end Alembic commands ###
