"""first revision

迁移 ID: 3e54cda0ba0d
父迁移:
创建时间: 2026-03-27 11:58:10.490988

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "3e54cda0ba0d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("osu_id", sa.Integer(), nullable=False),
        sa.Column("c_rank", sa.Integer(), nullable=True),
        sa.Column("g_rank", sa.Integer(), nullable=True),
        sa.Column("pp", sa.Float(), nullable=False),
        sa.Column("acc", sa.Float(), nullable=False),
        sa.Column("pc", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("osu_mode", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ranked_score", sa.BigInteger(), nullable=True),
        sa.Column("total_score", sa.BigInteger(), nullable=True),
        sa.Column("max_combo", sa.Integer(), nullable=True),
        sa.Column("count_xh", sa.Integer(), nullable=True),
        sa.Column("count_x", sa.Integer(), nullable=True),
        sa.Column("count_sh", sa.Integer(), nullable=True),
        sa.Column("count_s", sa.Integer(), nullable=True),
        sa.Column("count_a", sa.Integer(), nullable=True),
        sa.Column("replays", sa.Integer(), nullable=True),
        sa.Column("play_time", sa.Integer(), nullable=True),
        sa.Column("badge_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Info")),
        info={"bind_key": "nonebot_plugin_osubot"},
    )
    op.create_table(
        "SbUser",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("osu_id", sa.Integer(), nullable=False),
        sa.Column("osu_name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_SbUser")),
        info={"bind_key": "nonebot_plugin_osubot"},
    )
    with op.batch_alter_table("SbUser", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_SbUser_user_id"), ["user_id"], unique=False)

    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("osu_id", sa.Integer(), nullable=False),
        sa.Column("osu_name", sa.Text(), nullable=False),
        sa.Column("osu_mode", sa.Integer(), nullable=False),
        sa.Column("lazer_mode", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_User")),
        info={"bind_key": "nonebot_plugin_osubot"},
    )
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_User_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_User_user_id"))

    op.drop_table("User")
    with op.batch_alter_table("SbUser", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_SbUser_user_id"))

    op.drop_table("SbUser")
    op.drop_table("Info")
    # ### end Alembic commands ###
