"""first revision~

迁移 ID: 68a04ea31d05
父迁移: 
创建时间: 2026-03-30 16:17:52.764522

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '68a04ea31d05'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_osubot_infodata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('osu_id', sa.Integer(), nullable=False),
    sa.Column('c_rank', sa.Integer(), nullable=True),
    sa.Column('g_rank', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Float(), nullable=False),
    sa.Column('acc', sa.Float(), nullable=False),
    sa.Column('pc', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('osu_mode', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ranked_score', sa.BigInteger(), nullable=True),
    sa.Column('total_score', sa.BigInteger(), nullable=True),
    sa.Column('max_combo', sa.Integer(), nullable=True),
    sa.Column('count_xh', sa.Integer(), nullable=True),
    sa.Column('count_x', sa.Integer(), nullable=True),
    sa.Column('count_sh', sa.Integer(), nullable=True),
    sa.Column('count_s', sa.Integer(), nullable=True),
    sa.Column('count_a', sa.Integer(), nullable=True),
    sa.Column('replays', sa.Integer(), nullable=True),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('badge_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_osubot_infodata')),
    info={'bind_key': 'nonebot_plugin_osubot'}
    )
    op.create_table('nonebot_plugin_osubot_sbuserdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('osu_id', sa.Integer(), nullable=False),
    sa.Column('osu_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_osubot_sbuserdata')),
    info={'bind_key': 'nonebot_plugin_osubot'}
    )
    with op.batch_alter_table('nonebot_plugin_osubot_sbuserdata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_osubot_sbuserdata_user_id'), ['user_id'], unique=False)

    op.create_table('nonebot_plugin_osubot_userdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('osu_id', sa.Integer(), nullable=False),
    sa.Column('osu_name', sa.Text(), nullable=False),
    sa.Column('osu_mode', sa.Integer(), nullable=False),
    sa.Column('lazer_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_osubot_userdata')),
    info={'bind_key': 'nonebot_plugin_osubot'}
    )
    with op.batch_alter_table('nonebot_plugin_osubot_userdata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nonebot_plugin_osubot_userdata_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_osubot_userdata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_osubot_userdata_user_id'))

    op.drop_table('nonebot_plugin_osubot_userdata')
    with op.batch_alter_table('nonebot_plugin_osubot_sbuserdata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nonebot_plugin_osubot_sbuserdata_user_id'))

    op.drop_table('nonebot_plugin_osubot_sbuserdata')
    op.drop_table('nonebot_plugin_osubot_infodata')
    # ### end Alembic commands ###
